### ISSUE TITLE
v2.9 release tarball is uncompressed

### ISSUE THREAD

**Issue by lovell** [mm2/Little-CMS#139]
Ciao Marti, it looks like the latest Sourceforge-hosted `lcms2-2.9.tar.gz` file is a plain tar file and not gzip compressed as the filename might suggest.

https://sourceforge.net/projects/lcms/files/lcms/2.9/

Is this intentional?

**Comment by mm2** [comment]
Thanks for reporting. Should be fixed now...On 14 Nov 2017 13:41, Lovell Fuller <notifications@github.com> wrote:Ciao Marti, it looks like the latest Sourceforge-hosted lcms2-2.9.tar.gz file is a plain tar file and not gzip compressed as the filename might suggest.
https://sourceforge.net/projects/lcms/files/lcms/2.9/
Is this intentional?

**Comment by lovell** [comment]
Grazie!
