### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by boxerab** [mm2/Little-CMS#202]
I use Little-CMS in my image codec - here are a few compiler warnings I get when building under `clang`:

https://my.cdash.org/viewBuildError.php?type=1&buildid=1803786

**Comment by mm2** [comment]
This is a long list with many packages, I have just taken a quick overview to fing those related with lcms2. Sorry if I miss something.

Basically you got this warning on strncpy, not only on lcms2 but on many other packages:

`warning: ‘__builtin_strncpy’ output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
`

This is a false positive, at least in lcms2, as the code uses strncpy in a legit way.  Since there is nothing to fix but the diagnostic message, I would suggest to NOT use -Wstringop-truncation
