### ISSUE TITLE
Parametric tone curve for HDR EOTFs?

### ISSUE THREAD

**Issue by haasn** [mm2/Little-CMS#217]
I noticed that `Table 52`, the list of built-in parametric functions for `cmsTranParametricToneCurve`, does not include any curves resembling the structure of something like PQ (or HLG).

While I could define my own via a plug-in, or simply fall back to using a LUT-based transfer function, I was wondering if you were planning on providing something like this as part of the LittleCMS API itself.

Admittedly I also have no idea how well-equipped LittleCMS is to handling something like HDR inputs to begin with, since it requires handling values that conceptually go "above" the standard reference white, using an absolute luminance scale. For starters, it would suffice for my purposes if LittleCMS simply hard-clipped out-of-range brightness values the same way it clips out-of-gamut colors, and I would ensure that my inputs do not exceed the brightness range of the display device being targeted.

Right now, the way I treat HDR is to simply encode the entire HDR display range (from e.g. 0 to 1000 nits) as if it were a normal SDR display with gamma 2.2, when feeding it into the 3DLUT, but this has been reported to cause significant banding, and even the simple act of using a better transfer function should improve this. (In the absence of direct support for PQ/HLG, plan on using something *similar to* HLG, where I combine an SDR curve with a log section)

**Comment by mm2** [comment]
LittleCMS will do all you ask for without any change. Just make sure to use floats or doubles when you apply the transform to accomodate higlights and out ouf gamut values. Yes, lcms2 deals with HDR highlights in unbounded mode. LUT based HDR is also supported by using floating point elements.
Please see the discussion on this feature here http://www.littlecms.com/CIC18_UnboundedCMM.pdf
Otherwise you can add as many custom curves as you wish, but  note you cannot save those curves in ICC profiles because they are not i  the  ICC spec, so its use is somehow limited.
