### ISSUE TITLE
Can not load CGATS from file?

### ISSUE THREAD

**Issue by diuming** [mm2/Little-CMS#250]
lcms 2.11
macOS 11.0

Return NULL, When I using this function to load CGATS file.
`cmsIT8LoadFromFile(nil, "/path/cgats.txt")`

[GRACoLCoated1_ISO12647-7_ControlStrip2009_Ref.txt](https://github.com/mm2/Little-CMS/files/6176758/GRACoLCoated1_ISO12647-7_ControlStrip2009_Ref.txt)

**Comment by mm2** [comment]
The file is corrupted with lots of spurious " 

i.e.: 
"ORIGINATOR  ""IDEAlliance GRACoL Committee"""
where should be
ORIGINATOR  "IDEAlliance GRACoL Committee"

I've seen this kind of corruption when somebody tries to use Microsoft Excel to edit the CGATS.

Otherwise the lcms behaviour is fine, this is not a legal CGATS.17 file.

**Comment by diuming** [comment]
I got it and thanks
