### ISSUE TITLE
possible lcms bug in profile verification?

### ISSUE THREAD

**Issue by jcupitt** [mm2/Little-CMS#293]
Hello everyone, 

First, thank you for this nice library, libvips has relied on it for years. 

One of our users has reported strange behaviour here:

https://github.com/libvips/libvips/issues/2562

This JPG has an odd embedded profile. libvips is able to use the profile to convert pixels into PCS for processing, but using the profile to convert from PCS back to device space fails (you just get black pixels).

We call `cmsIsIntentSupported(profile, intent, LCMS_USED_AS_OUTPUT)` to check the profile before doing the PCS -> device space transform, and that returns TRUE, so lcms seems to think the profile is good.

Is there something else we should be checking? Or is this just a broken profile?

**Comment by mm2** [comment]
Hi John, 
That's Marti Maria, nice to meet you again. Thanks for reporting, indeed it was a bug introduced circa 2017 when trying to put some safaguards against divisions by zero. Unfortunately the code was discarding valid combinations as well. 
 Should be fixed by 8fb182279d9418b1477bb2bfe28e8ed4926e2318
Regards

**Comment by jcupitt** [comment]
Hi Marti, thank you very much for fixing this.

Yes, it's nice to interact again, libvips has been following your great work for many, many years now. I almost moved to Barcelona in the 90s to work at HP's large format printer division, so I feel a connection.

**Comment by mm2** [comment]
Seems fixed, so I close it
