### ISSUE TITLE
LCMS 2.13.1 Crash due to insufficient validation of return value from cmsDetectRGBProfileGamma

### ISSUE THREAD

**Issue by prrace** [mm2/Little-CMS#308]
Upgrading OpenJDK to use LittleCMS 2.13.1 I found that
the commit https://github.com/mm2/Little-CMS/commit/ab5029d60d5dc41a414e4acc472d024e3449d36a
was causing one of our "stress" tests to have a native crash inside LittleCMS.
The stress test creates lots of threads updating profiles (internally using cmsReadRawTag/cmswriteRawTag) and
then using them so it looked like a threading problem.
Although I don't at this point have a  native test case I found it to be nothing to do with stress testing nor
threading and to be a combination of a JDK mis-use of the LittleCMS APIs exposing a LittleCMS bug which
actually causes the crash.

OpenJDK provides and API to update the content of a tag for a profile.
For this it cmsReadRawTag/cmsWriteRawTag and copies a profile completely and instantiates a new one.
But this profile is never opened - and the use of the "Raw" APIs means it needs to be per the docs at
https://www.littlecms.com/LittleCMS2.13%20API.pdf which state on p67
Accessing tags as raw data
Those functions allows to read/write directly to the ICC profile any data, without checking anything.
As a rule, mixing Raw with cooked doesn't work, so writing a tag as raw and then reading it as cooked
without serializing does result into an error. If that is what you want, you will need to dump the profile to
memory or disk and then reopen it.

The test then uses this profile, but quickly cmsReadtag detects this and passes it off to error handling

        if (Icc->TagTypeHandlers[n] == NULL) goto Error;

where we now have two new lines which free the tag

Error:
    freeOneTag(Icc, n);
    Icc->TagPtrs[n] = NULL;

In theory this Error should be reported all the way up the chain and back to the client

But the bug seems to be in the implementation of cmsDetectRGBProfileGamma and in the handling of its return value.

This call is the first (in our test) which encounters the error it is specified like this
// Estimate gamma space, always positive. Returns -1 on error.
CMSAPI cmsFloat64Number CMSEXPORT cmsDetectRGBProfileGamma(cmsHPROFILE hProfile, cmsFloat64Number threshold);

and the call in cmsxform.c looks like this :

        cmsFloat64Number gamma = cmsDetectRGBProfileGamma(hProfiles[0], 0.1);

        if (gamma > 0 && gamma < 1.6)
            dwFlags |= cmsFLAGS_NOOPTIMIZE;

The problem is that "-1" is (a) not being handled as an error, because (b) it is overloaded in semantics

In some cases it returns -1 if calculations mean it seems invalid as a gamma.
But critically in other cases it is trying to communicate that the profile is invalid.

This is the case when 
     xform = cmsCreateTransformTHR(ContextID, hProfile, TYPE_RGB_16, hXYZ, TYPE_XYZ_DBL, 
                                     INTENT_RELATIVE_COLORIMETRIC, cmsFLAGS_NOOPTIMIZE);
 
     if (xform == NULL) { // If not RGB or forward direction is not supported, regret with the previous error
         cmsCloseProfile(hXYZ);   
        return -1; /// <<< This is a fatal error but can't be distinguished from "unsupported.
   }     

This error didn't use to be fatal but now the freeOneTag() call makes it so.

Clearly the latter case needs to be handled but isn't.

I also notice that in cmsDetectRGBProfileGamma the return from
    hXYZ = cmsCreateXYZProfileTHR(ContextID);
is not checked - this looks like it should be a fatal error too - although I did not see that fail here.

So LCMS continues to use the profile, dives back in and I think because it has now free this tag it fails this test
in cmsReadtag() :-
    if (Icc -> TagPtrs[n]) {

so skips over the whole block and ends up at

    io = Icc ->IOhandler;
    // Seek to its location
    if (!io -> Seek(io, Offset)) {

where io is null and de-referencing it we have a crash.

So  there are multiple things that can be done
1) OpenJDK can avoid provoking the issue (to be fixed there of course!)
2) LCMS should update the implementation and handling of cmsDetectRGBProfileGamma to be able communicate a fatal error
3) LCMS should probably update at least one more place where it seems error handling is missing - the return from cmsCreateXYZProfileTHR
4) In at least the one place above in cmsReadTag verify io != null and if it is head back to Error:
This avoids the crash so is useful but 

(2) is the tricky one from a coding aesthetics standpoint. We want to be able to use the flaot return value to
(a) be a valid gamma to use
(b) indicate to ignore gamma
(c) indicate there's a serious problem

(a) should be when gamma is >= 0 (not just >0 if I have things right)
(b) could be the existing -1
(c) could be <-1 .. I suggest at least -2 so there's no FP issues !

**Comment by mm2** [comment]
Thank you SO MUCH for the PR and specially for the detailed explanation. I will take a couple of days to see if I could make it more bullet-proof in the sense that an ill-formed profile would not behave differently the second time you use it. Otherwise your solution is fine to me.

**Comment by mm2** [comment]
Ok, such detailed explanation deserves some notes on how I solved the bug and what was happening.

The bug was somehow more important that detect gamma. The gamma detection function returns the gamma value or -1 if it cannot do the guessing. 0 is valid, although not very common, is for profiles that returns always same value, like the NULL profile for example.  If the profile is corrupted then gamma cannot be guessed and -1 should be returned. This should have nothing to do with the segfault, but you discovered it actually has. Good, because it helped me to find a more general bug.

The steps to reproduce the bug was this: **If you create a built-in profile, then modify the profile by using cmsWriteRawTag and the data you put there was bogus, that profile could cause a segfault when used in transforms.**

This was harmless in terms of exploits because as soon as you serialize the profile (write it to disk or memory) the bug is gone. 
Sure thing you could create a  program that  forces a segfault in this way, but just passing a block of garbage to any function using cmsHPROFILE would cause same effect, and with less effort. **You CANNOT create a segfault embedding a profile on an image. No CVEs here**.

Regarding the technical details, It was segfaulting because the built-in profiles have iohandlers set to NULL. Using NULL for iohandler makes sense in this case because built-in profiles are not supposed to be created from any serialized media, but instead by a program or lcms itself populating the tags directly. So, a built-in already have all necessary tags and all are already loaded in memory. 

But what happens if one of this tags comes corrupted?  The code sets the tag pointer to NULL and free the tag. Next call to cmsReadTag would find the NULL and, in mistake, think the tag is not yet read, so it tries to read it by using the iohandler and since iohandler is NULL hence the segfault.

The solution is simple once you know the error source: if iohandler is NULL, just abort everything saying that this is a corrupted built-in.

This is what 458bffeba9a74d6069659768b2c3df20a4aeb495 addresses. Hope that would solve the issue.

Thanks again for reporting.

**Comment by mm2** [comment]
should be fixed right now
