### ISSUE TITLE
Some questions with CGATS it8 output

### ISSUE THREAD

**Issue by diuming** [mm2/Little-CMS#310]
version 2.13.1

I encountered some problems, could I asking you some questions?

Q1)How do I insert a blank line?
      I trying cmsIT8SetPropertyStr(cgats, "", "") function, but it's no effect.

Q2)How do I move `NUMBER_OF_FIELDS` close to `BEGIN_DATA_FORMAT`?

Q3)How do I move  `NUMBER_OF_SETS` close to `BEGIN_DATA`?

Q4)There is a space at every start of lines in `BEGIN_DATA_FORMAT` and `BEGIN_DATA` sessions.
 How do I prevent it?

Please take a look below image. thanks

brief code
---
```
cmsIT8SetPropertyStr(cgats, "ORIGINATOR", "ORIGINATOR")
cmsIT8SetPropertyStr(cgats, "MANUFACTURER", "MANUFACTURER")
.
.
.
cmsIT8SetPropertyDbl(cgats, "NUMBER_OF_FIELDS",  fields)
for idx in formats {
    cmsIT8SetDataFormat(cgats, idx, "some_format")
}

cmsIT8SetPropertyDbl(cgats, "NUMBER_OF_SETS", sets)
for row in rows {
    ...
    cmsIT8SetDataRowColDbl(cgats, row, format_idx, value)
}
cmsIT8SaveToFile(cgats, "path")
cmsIT8Free(cgats)
```

![Screen Shot 2022-03-06 at 7 21 57 PM](https://user-images.githubusercontent.com/39903550/156923873-67ad874a-971a-4e18-ac3a-aeed61f1a595.png)

**Comment by mm2** [comment]
The idea is the parser would generate a valid CGATS file, not a human readable beautified one. Since the hard part is to read it, I would suggest to use fprintf() to generate the file. In this way you have all the control you want and the effort is almost the same. Quite different thing is to read and validate the CGATS file, in that case fscanf() is clearly not enough.

**Comment by diuming** [comment]
I got it, thanks!
