### ISSUE TITLE
Checksum for 2.8 SourceForge

### ISSUE THREAD

**Issue by ilovezfs** [mm2/Little-CMS#88]
Hi,
We just got an issue filed over at Homebrew about the checksum recorded in the little-cms2.rb formula file not matching the checksum of the downloaded archive, so Homebrew errored out due to the mismatch: https://github.com/Homebrew/homebrew-versions/issues/1321

I happened to still have a copy of the original in my cache, and noticed that the difference appears to be just that the original archive was not gzip compressed, while the newly uploaded one is.

In the future, it would be really helpful if you could actually bump the version, or at least add a release note on SourceForge explaining why the checksum changed, since we hard code the checksum for security purposes, and then have to wait for a user to notify us that the checksum "mysteriously" changed, then go ping upstream to find out what happened, etc., and make sure there hasn't been a security compromise.

Thanks

**Comment by mm2** [comment]
Hi, it seems you catched early the mistake, so your automated system is working. Good. The first file was not compressed and some people complained on that. Since the contents of the tarball is unchanged, I think a version bump is not necessary. There is a change in the package but not in the code. We also distribute a zip file and version number is same. Regards.
