### ISSUE TITLE
Q: cmsDoTransform(): using same buffer for in and out

### ISSUE THREAD

**Issue by LebedevRI** [mm2/Little-CMS#93]
Hi.

Unfortunately [LittleCMS2.7 tutorial.pdf](http://www.littlecms.com/LittleCMS2.7%20tutorial.pdf) is not verbose-enough.

I would like to get a clarification about:
```
It is safe to use same block for input and output, but only if the input and output are coded in
same format. For example, you can safely use only one buffer for RGB to RGB but you cannot use
same buffer for RGB as input and CMYK as output.
```

In particular, that does mean that i can **not** use the same buffer to convert from `TYPE_RGBA_FLT` to `TYPE_LabA_FLT`, but i can use the same buffer to convert from `TYPE_RGBA_FLT` to `TYPE_RGBA_FLT`?

**Comment by mm2** [comment]
You can reuse the same buffer as long as the output pixel size is same as input pixel size. So RGBA_FLT to LABA_FLT is ok, but CMYK_FLT to LAB_FLT is not.

The reason is the engine keeps two pointers, one for input and other output. If the output pixel size is less then the input pixel size, input will be overwritten when applying color transform.

**Comment by LebedevRI** [comment]
> You can reuse the same buffer as long as the output pixel size is same as input pixel size.

Awesome!
Thank you for clarifying this. :)
